services:
  - type: web
    name: webpush-dashboard
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile

    envVars:
      - key: DATABASE_URL
        value: <YOUR_DATABASE_URL>
      - key: SECRET_KEY
        value: <YOUR_SECRET_KEY>
      - key: JWT_SECRET
        value: <YOUR_JWT_SECRET>
      - key: DASHBOARD_DOMAIN
        value: https://your-dashboard.onrender.com
